blueprint:
  name: Bewegungsmelder mit Sperre
  description: Licht über Bewegungsmelder schalten mit Sperrtaster
  source_url: https://github.com/brstgt/ha-blueprints/blob/main/automation/motion_bypass.yaml
  domain: automation
  author: Benjamin Roth
  input:
    motion_entity:
      name: Bewegungsmelder
      selector:
        entity:
          filter:
            - domain:
                - input_boolean
            - device_class:
                - motion
              domain:
                - binary_sensor
          multiple: false
    lux_entity:
      name: Helligkeit Sensor
      default: 0
      selector:
        entity:
          domain:
            - sensor
          device_class:
            - illuminance
          multiple: false
    lux_level:
      name: Helligkeit Schwelle
      description:
        Licht geht an, wenn Helligkeit unterhalt dieser Schwelle ist
      default: 100
      selector:
        number:
          min: 0.0
          max: 1000.0
          step: 1.0
          mode: slider
    lock_entity:
      name: Sperrtaster
      selector:
        entity:
          filter:
            - domain:
                - input_boolean
            - domain:
                - switch
            - domain:
                - binary_sensor
          multiple: false
    light_target:
      name: Licht
      selector:
        target:
          entity:
            - domain:
                - light
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 120
      selector:
        number:
          min: 0.0
          max: 3600.0
          unit_of_measurement: seconds
          step: 1.0
          mode: slider
mode: queued
triggers:
  - trigger: state
    entity_id:
      - !input lock_entity
    to: 'on'
    id: Sperren An
  - trigger: state
    entity_id:
      - !input motion_entity
    to: 'on'
    id: BM An
  - trigger: state
    entity_id:
      - !input motion_entity
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: !input no_motion_wait
    id: BM Aus
  - trigger: state
    entity_id:
      - !input lock_entity
    to: 'off'
    id: Sperren Aus
  - trigger: state
    entity_id:
      - !input lux_entity
    id: Helligkeit
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Sperren An
        sequence:
          - action: light.turn_on
            metadata: {}
            data: {}
            target: !input light_target
      - conditions:
          - condition: trigger
            id:
              - BM An
              - Helligkeit
          - condition: state
            entity_id: !input motion_entity
            state: "on"
          - condition: numeric_state
            entity_id:  !input lux_entity
            below: !input lux_level
        sequence:
          - action: light.turn_on
            metadata: {}
            data: {}
            target: !input light_target
      - conditions:
          - condition: trigger
            id:
              - Sperren Aus
        sequence:
          - action: light.turn_off
            metadata: {}
            data: {}
            target: !input light_target
      - conditions:
          - condition: trigger
            id:
              - BM Aus
          - condition: state
            entity_id: !input lock_entity
            state: 'off'
        sequence:
          - action: light.turn_off
            metadata: {}
            data: {}
            target: !input light_target
